const prefix = process.env.NEXT_PUBLIC_BASE_PATH || '';

export { prefix };

// ...
// import { prefix } from '../../utils/prefix.js';
// ...
//     <img src={`${prefix}/someimage.jpg`} alt='some alt text' />
// ...
